### PR TITLE
Add support for multi_tenant_enabled setting

### PR DESCRIPTION
**Pull request by tjkb**
# Submit a pull request

## CLA

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [x] The code changes follow best practices
- [x] Code changes are tested (add some information if not applicable)

## Description of the pull request

Make it possible to read/write the `multi_tenant_enabled` setting via `AppSettings`/`AppSettingsWithDetails` to support multi tenancy scenarios. Enhanced existing unit tests to test this new setting.

### CODE REVIEW

**Comment by tjkb** [comment]
I guess it's known that the unit tests fail when no api key and secret are provided. Probably it makes no sense to run them here.

**Comment by tjkb** [comment]
What about this PR @ferhatelmas ?

**Review by ferhatelmas — APPROVED** [review]
LGTM :+1:

**Comment by ferhatelmas** [comment]
https://www.nuget.org/packages/stream-chat-net/0.6.0

thanks for your PR.

**Pull request merged**
